### ISSUE TITLE
Change search results sort options to relevance, artist, title (remove year)

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#17]
Currently the options are sort by relevance, year, author, title

**Comment by thisismattmiller** [comment]
All of the dropdowns seem to have broken... not sure what is going on will need to look into it. Something with the bootstrap data hooks not being bound to the events.

**Comment by thisismattmiller** [comment]
Dropdowns fixed! but haven't changed sort options yet

**Comment by thisismattmiller** [comment]
Sort working and removed date.
