### ISSUE TITLE
Data issue: British Museum URIs not displayed

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#25]
British Museum URIs should go in the data sources section

**Comment by thisismattmiller** [comment]
The wireframe now has it next to the museum link, move it? See http://localhost:3000/catalog/0000691-Berenson

**Comment by thisismattmiller** [comment]
There is another link that should go into it called "Link" For example: http://104.236.214.160/catalog/001271D-Berenson Need to fix.

**Comment by thisismattmiller** [comment]
Don't say "Link" it us just "View Record"

**Comment by lklic** [comment]
this is working for me
