### ISSUE TITLE
Add plate number to IIIF image caption

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#29]

**Comment by thisismattmiller** [comment]
Where do we want this displayed?

**Comment by thisismattmiller** [comment]
Display the caption of the Plate or the BM under the image area

**Comment by thisismattmiller** [comment]
Plate name : "Plate XYM"
Museum: "Image from the XX Museum" - To allow other museums data.

**Comment by thisismattmiller** [comment]
done

**Comment by thisismattmiller** [comment]
Fix when there are multiple images - 0001035-Berenson

**Comment by thisismattmiller** [comment]
done
