### ISSUE TITLE
inventory number field indexing

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#30]
inventory numbers

need specific inventory numbers selector/dropdown for search
add inventory number to all fields search—boost that field

flexible search for that field
allow search for partials, ignore punctuation, ignore case

**Comment by thisismattmiller** [comment]
New inventory number search.

For example the inventory number "1860,0616.29" can be searched "1860 0616.29" or "1860 0616 29" or "0616.29" or "0616 29" ect.

The same will also work in "keyword" search mode.

Added inventory number to the search result page
