### ISSUE TITLE
Write overview on the transformation from Quads to Blacklight Index

### ISSUE THREAD

**Issue by thisismattmiller** [villaitatti/florentine-drawings#34]

**Comment by thisismattmiller** [comment]
To facilitate the use of Blacklight as the discovery interface we needed to convert the graph data for each Berenson entity into a single Solr document . This is effectively flattening the graph model into a single document composed of a number of properties. This task is complicated by two factors: we store the data across four named graphs, one for each edition and a project data graph and the general recursive nature of working with triples.

The first problem is solved by querying each edition graph separately and then combining the data together at the end of the process under year labeled fields, for example each solr document had three verso title field:
- verso_title_1903_t
- verso_title_1938_t
- verso_title_1961_t

Which are all indexed separately and included in the fields tied to a "Title" search.
We also added a number of new fields to the index to support the data model from notes, techniques, provenance data, image assets, etc, that appear on each record page.

To quickly index the data we do not execute thousands of SPARQL queries to load all the data for the Berenson entities we simply download all the triples from the endpoint for each graph and process them in bulk. The recursiveness problem, for example having to dereference the label of an institution which is stored in another statement, is done by building internal lookup tables at process time for the literals. This does require that you pre-process all the triples to build those lookup tables before constructing Solr documents, basically processing the dataset twice. This approach works at the scale of our dataset, being able to convert the triples over into a Solr documents and push them into the index in around 5 to 10 minutes depending the server specs. If the dataset was much larger however it would necessitate constructing more detailed SPARQL queries for each Solr document.

The opportunity for enrichment is enabled at the time of indexing by dereferencing external URIs such as VIAF, ULAN or AAT for their full data (and then cache it for later use) and choosing to included that new data in the index. For example if we wanted to include the alt-terms used for techniques in addition to its pref-label we could push those literals into the Solr index only, without having to store them in the our triple store.

---

Customizations to the interface focused on displaying and organizing the new data fields introduced with work mainly focused on the item display page. Through a number of design iterations and feedback from domain specialists we settled on the layout which accommodates displaying data for a single record but also able to convey the historic data from three different editions. We added an asset viewer using open Seadragon powered by an IIIF server as well as some other static pages and customization to theme the site to the current Itatti website.

On the backend a number of new fields were added to the Solr config with corresponding relevancy boots. And we introduced a couple of new search methods that required some more advanced tokenizing such as the search by Inventory Number feature.

**Comment by thisismattmiller** [comment]
Okay here is the writeup, let me know if you would like parts expanded or other pieces covered.

**Comment by aprovo** [comment]
Sorry for my delay--this is great! Could you expand a little bit on the last paragraph about new fields and new search methods?

It'd also be great to have a few screenshots--I can do these if you tell me which files would be best. I was thinking an image of the lookup tables and also the main Solr document.
