### ISSUE TITLE
Display images on search results page

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#35]
apply same logic as in individual record page:

if an item has a 1903 plate number: IIIF derivative
museum image: jpeg
1903 page number: also a jpeg, 500 px image on S3 bucket; clicking on the image will take you to the Harvard page turn viewer

**Comment by thisismattmiller** [comment]
@lklic Will generate thumbnails for every record and name them [Berenson Catalogue Number].jpg on s3 and will be just linked dynamically in the app.

**Comment by lklic** [comment]
I created another ticket for this, logic is different for search results page.
