### ISSUE TITLE
thumbnails on results page

### ISSUE THREAD

**Issue by lklic** [villaitatti/florentine-drawings#36]
to add an IF statement to display a thumbnail on the results page.

should be 200px high.

So far I have ~400 images in the thumbs folder but will be adding more as we get more images. If there is no image we should not display anything.

Format is:
https://s3-eu-west-1.amazonaws.com/florentinedrawings/thumbs/ <berenson catalog number>

sample image:
https://s3-eu-west-1.amazonaws.com/florentinedrawings/thumbs/0000670-Berenson.jpg

**Comment by thisismattmiller** [comment]
Added images for review

**Comment by thisismattmiller** [comment]
Some of the images don't seem to line up with their plate, need to discuss.
