### ISSUE TITLE
The local entities should show up in the datasources on item page

### ISSUE THREAD

**Issue by thisismattmiller** [villaitatti/florentine-drawings#39]

**Comment by aprovo** [comment]
Hi Matt--just a note to make sure that the URI path for the local entities is /resource and not /id

http://data.itatti.harvard.edu/id/florentinedrawings/0000192-Berenson.html
should be
http://data.itatti.harvard.edu/resource/florentinedrawings/0000192-Berenson

**Comment by thisismattmiller** [comment]
![image](https://cloud.githubusercontent.com/assets/1336458/24074841/e803e044-0be6-11e7-9f77-56f828b719aa.png)

The VIAF label will change to VIAF/I Tatti label when local entities are in the recortd
