### ISSUE TITLE
image captions fix

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#40]
Hi Matt! I noticed a couple of things to do with image captions:

add “recto” or “verso” to the image caption
display only the caption for image being shown (currently, all captions are visible)

**Comment by thisismattmiller** [comment]
Is this issue complete? I think it is

**Comment by lklic** [comment]
we are still missing recto/verso info on captions

**Comment by thisismattmiller** [comment]
Like this?

![image_captions](https://cloud.githubusercontent.com/assets/1336458/24472190/ce603aac-1492-11e7-9ba1-e4088bf6ce99.gif)

**Comment by aprovo** [comment]
That looks great!
