### ISSUE TITLE
artists facet includes duplicate names

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#42]
is it possible to have the artist facet count the ULAN URI instead of the label, and display just one of the labels (in order of priority, 1961, 1938, or 1903)?
background: in each graph, we have a different label for the ULAN URI to reflect the spelling of that artist's name in each edition. So for example, we have both:
Alessio Baldovinetti
and
Alesso Baldovinetti

**Comment by aprovo** [comment]
@thisismattmiller need anything from me for this?

**Comment by thisismattmiller** [comment]
Should be fixed on my local, but cannot search on the incorrect spelling of the name right now FYI.
