### ISSUE TITLE
http://victor_koch and http://wild-blundell_collection

### ISSUE THREAD

**Issue by thisismattmiller** [villaitatti/florentine-drawings#43]
http://victor_koch and http://wild-blundell_collection are in the project graph as URIs, they should have the be updated to have the full URI

**Comment by lklic** [comment]
@aprovo can you clarify the URLs to use for these collections? I can push the update to the data.

**Comment by aprovo** [comment]
Oops--yes. I'll check on this over the weekend and get you updated URLs.

**Comment by aprovo** [comment]
They should be http://data.itatti.harvard.edu/resource/florentinedrawings/entity/wild-blundell_collection and http://data.itatti.harvard.edu/resource/florentinedrawings/entity/victor_koch

These two slipped by me when I was cleaning collection names--sorry about that!

**Comment by lklic** [comment]
All set, added to the project 2016 graph. Will need to run a rake task to have it reflected in blacklight
