### ISSUE TITLE
Sort Artist and Location facets alphabetically instead of by count

### ISSUE THREAD

**Issue by aprovo** [villaitatti/florentine-drawings#7]
Sort these two facets alphabetically by default; when users click more, allow option to sort by count.

**Comment by thisismattmiller** [comment]
changed the sort

**Comment by aprovo** [comment]
Artists facet looks great! Location is still sorting by count, though.

**Comment by lklic** [comment]
I prefer to keep the sort for the locations by count, as it seems to be more useful to see the quantity by location. Closing this ticket in the interest of time, feel free to open if you think it's important to sort by name.
